version: "3.9"

services:
  database:
    image: postgres:13.6-alpine
    env_file:
      - .env
    expose:
      # Deixa a porta do banco de dados acessivel 
      # para ferramentas externas como o dbeaver por exemplo.
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups

  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./archive/data:/archive/data
      - ./archive/django_static:/archive/django_static
    depends_on:
      - database

  frontend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./frontend:/app
    stdin_open: true
    command: yarn dev
    # ports:
    #   - 3000:3000

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./archive/django_static:/var/www/django_static
      - ./archive/data:/var/www/data
    depends_on:
      - backend
      - frontend
